version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: soccorso-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: soccorsodb_we
      MYSQL_USER: soccorso_user
      MYSQL_PASSWORD: soccorso_pass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./soccorso_mariadb.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - soccorso-network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    image: amazoncorretto:21
    container_name: soccorso-app
    restart: always
    working_dir: /app
    volumes:
      - ./target:/app
    command: ["java", "-jar", "/app/soccorso-web.jar"]
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "8081:8080"
    networks:
      - soccorso-network

volumes:
  db_data:

networks:
  soccorso-network:
