services:
  mariadb:
    image: mariadb:latest
    container_name: soccorso-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: soccorsodb_we
      MYSQL_USER: soccorso_user
      MYSQL_PASSWORD: soccorso_pass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./src/main/resources/db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - soccorso-network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: soccorso-web:latest
    container_name: soccorso-app
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "8081:8080"
    networks:
      - soccorso-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/soccorsodb_we
      SPRING_DATASOURCE_USERNAME: soccorso_user
      SPRING_DATASOURCE_PASSWORD: soccorso_pass

volumes:
  db_data:

networks:
  soccorso-network:
